### ISSUE TITLE
Confirm that the swift comments added for router, sys, etc. follow the convention required by SwiftDoc

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#135] opened 2016-02-22 20:16 UTC
Info on SwiftDoc here: swiftdoc.org

**Comment by rfdickerson** [comment] 2016-02-25 15:24
I can confirm that inside of our .swiftdoc files (KituraRouter.swiftdoc) allow of our documentation exists. However, it appears that the standards regarding documentation generation are still non-standard. [See proposal](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md#documentation-generation). I have not been able to find the standards set by http://www.swiftdoc.org

**Comment by rolivieri** [comment] 2016-02-25 15:32
@rfdickerson Is there a tool available today (like the javadocs tool) that could be used to test the documentation comments you added to the code? If there isn't and there is no standard yet, then maybe we should defer issue #119.

**Comment by rfdickerson** [comment] 2016-02-25 15:34
Should I try this tool?

https://github.com/SwiftDocOrg/swiftdoc-parser

**Comment by rfdickerson** [comment] 2016-02-25 16:41
There's a good chance that the swiftdoc-parser doesn't work on Swift.org projects that have C-modules. For instance, when I run the index.js file on our code:

```
➜  Kitura git:(master) ✗ ~/mil/swiftdoc-parser/index.js ~/mil/KituraProject/Kitura/Sources/KituraSample/main.swift

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/pcre'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/rfdickerson/mil/swiftdoc-parser/node_modules/pcre/lib/pcre.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Is there supposed to be a directory called ./.build/Release/pcre ? I tried to compile using 'swift build -configuration=release. Yes, it builds to ./build/release, but doesn't fix the above issue.

**Comment by rfdickerson** [comment] 2016-02-27 15:34
I filed an issue against their parser:

[Support for Swift Package Manager supported project with C ModuleMaps #7](https://github.com/SwiftDocOrg/swiftdoc-parser/issues/7)

**Comment by natecook1000** [comment] 2016-03-06 02:46
@rfdickerson, the swiftdoc.org project is intended solely to parse and present documentation for the Swift standard library in a more usable format, not for general purpose documentation. I'd suggest you take a look at [Jazzy](https://github.com/realm/jazzy), which does seek to create usable docsets from documentation comments in a project's source.

Hope that helps!

**Comment by natecook1000** [comment] 2016-03-06 02:50
For more information, Apple has [official documentation](https://developer.apple.com/library/ios/documentation/Xcode/Reference/xcode_markup_formatting_ref/index.html#//apple_ref/doc/uid/TP40016497) on how documentation comments can/should be written, others ([including me](http://nshipster.com/swift-documentation/)) have written on the subject as well.

**Comment by dfirsht** [comment] 2016-03-10 22:47
@rfdickerson have you looked at the official documentation above?

**Comment by rfdickerson** [comment] 2016-03-10 23:08
@billabt any reason why we are using for codeblocks above function definitions:

///
/// This is a comment
///

vs.

/**
This is a comment
*/

I checked and both work, but not sure which is "better". The documentation for [code blocks](https://developer.apple.com/library/ios/documentation/Xcode/Reference/xcode_markup_formatting_ref/CodeBlocks.html#//apple_ref/doc/uid/TP40016497-CH12-SW1) on Apple's site uses the later. Thoughts?

**Comment by billabt** [comment] 2016-03-11 01:08
No good reason other than personal preference. Three /'s is easier to type and in my personal opinion looks better. Finally, the triple is for one line only, whereas the /** needs to be closed with a */ which could have unintended consequences. Also, by the way, two /'s is a comment, three /'s is a documentation block. The two / variety is internal only.

**Comment by dfirsht** [comment] 2016-03-11 20:04
@rfdickerson Are you planning on making any changes to this or is it ok to close it?

**Comment by rfdickerson** [comment] 2016-03-11 20:19
Let's close this issue for now. We can always open another issue if we want the /** syntax. I'm still not sure what is best, it's mostly aesthetic anyhow...

**Closed by rfdickerson** 2016-03-11 20:19 UTC
Labels: documentation
