### ISSUE TITLE
HTTPS produces SSL write errors (linux), SSL read errors (OS X)

### ISSUE THREAD

**Issue by jnigro** [IBM-Swift/Kitura#1036] opened 2017-03-18 13:39 UTC
Hi,

I have setup a Kitura/HTTPS server. Both under Linux and OS X. When serving a file through the StaticFileServer() middleware, if it is not too small, the transfer is usually truncated and errors are logged to the screen.

The errors differ between Linux and OS X. With Linux it is all WRITE errors and with OS X, it is all READ errors:

**OS X** (SSL read errors)
```
[2017-03-18T12:28:55.723+01:00] [ERROR] [IncomingSocketHandler.swift:148 handleRead()] Read from socket (file descriptor 8) failed. Error = Error code: -9806(0x-264E), ERROR: SSLRead, code: -9806, reason: errSSLClosedAbort.
[2017-03-18T12:28:55.855+01:00] [ERROR] [IncomingSocketHandler.swift:148 handleRead()] Read from socket (file descriptor 7) failed. Error = Error code: -36(0x-24), ERROR: SSLRead, code: -36, reason: errSecIO.
```

**Linux** (SSL write errors)
```
[2017-03-18T11:32:15.896Z] [ERROR] [IncomingSocketHandler.swift:265 handleWriteHelper()] Write to socket (file descriptor 7) failed. Error = Error code: 336195711(0x1409F07F), ERROR: SSL_write, code: 336195711, reason: bad write retry.
```

I have assemble a minimum project that demonstrate the problem. It is available at:

`https://github.com/jnigro/kitura-ssl_bug
`

The project works both with Linux and Mac. Certificates are already created (password = "password"). In the Certs directory there is also the script I used to automate the certificate creation.

The project contains a large image that can be used to easily reproduce the problem:

`https://localhost:8090/large.jpg`

Versions used:

software|Version
------|-------
Kitura | 1.6.2
Swift | 3.0.2
OS X | OS X 10.11 and OS X 10.12
Linux|docker ibmcom/kitura-ubuntu (14.04.5)

For futher details, please check the repository's README.md

Thanks!

**Comment by na-gupta** [comment] 2017-03-20 22:13
@jnigro  I am able to reproduce the problem on os x, and have submitted a PR (IBM-Swift/BlueSSLService/pull/20) to a dependent repo to fix the issue.

The `SSLRead, code: -9806` errors probably will not go away on os x without some external work, but can be safely ignored as long as the functionality works after this fix.

However, I am not able to reproduce the problem on linux. Can you confirm that the download fails  on linux as well for you?

**Comment by jnigro** [comment] 2017-03-21 09:10
Hi na-gupta,

Yes, I can confirm the download fails on Linux. I was using docker, but now I also tried on a full Ubuntu 14.04 installation. Problem is still there.

Are you using 14.04? I think I read in some other thread, that you were using 16.x? Could that be the difference. If I have time today, I will try to test it on Ubuntu 16.x and report back.

On the other side, I tried your fix on Mac. As you said, the transfer now completes successfully, although the errors are still logged.

Thanks!

**Comment by jnigro** [comment] 2017-03-21 11:14
Adding to my previous reply: I had a little time to test it also on Ubuntu 16.04.02 LTS. Still the same write errors (code 336195711).

**Comment by na-gupta** [comment] 2017-03-21 16:35
I am using Ubuntu 14.04 too. Could you please try deleting your Packages and build folders, rebuild the project and try again. Also, if you still get the error, could you please paste the output of `wget https://localhost:8090/large.jpg --no-check-certificate` here. Thanks

**Comment by jnigro** [comment] 2017-03-21 17:18
Hello again. I think I have good information on how you can reproduce the problem now. I went ahead and did what you asked, even though I already cleaned my build and Packages directory in the past with no joy. However, I was surprised when this time the errors did not appear.

That made me look harder on what I was doing differently now. In the past I was connecting from Chrome in a remote Mac computer. So, to isolate the problem, I went back to my Mac and tried to transfer the file using wget. The errors did appear again. It took it 8 tries for wget to get the file. The first 7 tries aborted with 5%, 39%, 7%, 43%, 70%, 97%, 7% and finally 100%. There is one error logged to the server's output for each try.

With this information, the problem is either being triggered by serving to the remote interface (instead of the loopback interface), or because of something the OS X client side does differently. Either way, I think you will be able to reproduce it now.

I am attaching 3 files:

File|Description
---|---
build.txt|A full log of the entire process. From cloning the sample project, to running the server.
ok-wget-linux-localhost.txt|The wget output when getting the file from the same Linux host
error-wget-macosx.txt|The wget output when getting the file from a remote OS X computer. It also includes the errors logged when wget failed 7 times.


I hope this helps. Cheers

[ok-wget-linux-localhost.txt](https://github.com/IBM-Swift/Kitura/files/859055/ok-wget-linux-localhost.txt)
[build.txt](https://github.com/IBM-Swift/Kitura/files/859056/build.txt)
[error-wget-macosx.txt](https://github.com/IBM-Swift/Kitura/files/859057/error-wget-macosx.txt)

**Comment by na-gupta** [comment] 2017-03-21 21:55
I was able to reproduce the problem and submitted another pull request (https://github.com/IBM-Swift/BlueSSLService/pull/21) to BlueSSLService, this time with a fix for openssl on linux. Hopefully this resolves the issue once it's merged and tagged. Thanks!

**Comment by na-gupta** [comment] 2017-03-22 14:20
@jnigro This has been fixed in SSLService-0.12.29. Please verify it works ok now on both linux and mac. Thanks!

**Closed** 2017-03-22 14:50 UTC

**Comment by jnigro** [comment] 2017-03-22 16:10
Thank you na-gupta. That was fast! I already checked and works both on Linux and Mac. OS X continues to  complain of errors, but the transfer is indeed successful.

Thank you!

**Comment by kapsy** [comment] 2017-03-31 05:45
Thank you to everyone who raised and fixed this! I too was getting a `bad write retry` error - deleting all packages to force an upgrade to the latest SSLService worked like a charm.
