### ISSUE TITLE
Evaluate alternative JSON packages

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#422] opened 2016-04-29 15:00 UTC
We've had ongoing problems with SwiftyJSON.

Investigate alternatives, because the Swift ecosystem has evolved since we adopted SwiftyJSON.

Particularly, look at https://github.com/postmates/PMJSON which seems to be high-quality and has no dependency on Foundation.

**Comment by rfdickerson** [comment] 2016-04-29 15:01
Agreed. Here's another for inspiration:

https://github.com/Zewo/JSON

**Comment by dfirsht** [comment] 2016-04-29 15:05
While I like the idea of moving away from SwiftyJSON, PMJSON doesn't look that active, their latest release was to support 02-08.

**Comment by ianpartridge** [comment] 2016-04-29 15:13
Once you've written a JSON library, there's not much else to do with it.  It would need porting to Swift 3 but that shouldn't be a big deal.

**Comment by rolivieri** [comment] 2016-04-29 16:06
This is certainly worth exploring and discussing. However, just to clarify: the root cause of the problems we’ve had with SwiftyJSON were due to 1) a bug in the Swift compiler and 2) missing functionality in Foundation (Linux). The latter forced our team to create custom logic in the LclJSONSerialization.swift file (which brought up to the surface the bug in the compiler). LclJSONSerialization.swift is not part of the official SwiftyJSON library (instead, it is a file that the Kitura team wrote as stopgap solution). Once Foundation (Linux) provides the missing functionality, the team can eliminate the need for LclJSONSerialization.swift.

Maybe the question is bigger than whether to use SwiftyJSON or PMJSON. Maybe the question is do we prefer using libraries that leverage Foundation or libraries that are entirely written in Swift with no dependencies on Foundation? Also, this is probably one of the main differences between Kitura and other Swift web frameworks that are out there. I believe that the ones that are pure Swift are not dependent on Foundation, while Kitura is. I see pros and cons to both approaches. iOS developers are very familiar with Foundation… hence, being dependent on Foundation classes may attract those developers to write code for the server. For instance, they are already familiar with NSURLSession (and friends) as opposed to having to learn a new networking API.

**Comment by ianpartridge** [comment] 2016-04-29 16:21
I think given that Foundation on Linux is incomplete, has incompatibilities, and is relatively untested, at the moment we're better served by using pure Swift libraries where possible, provided we have an appropriate level of confidence in their quality.

**Comment by flangel** [comment] 2016-05-01 14:20
Hi,

I asked myself the same questions when implementing first projects with Kitura, and found https://github.com/hkellaway/Gloss  to be a very nice to use library. 

One question i like to raise : Will Apple Swift team ever incorporate JSON parsing solution ? If its not on the roadmap, perhaps adopt one of the JSON parsers currently available and bring a) the developer and b) the library under the Kitura umbrella, providing the developer community with the promise of long term support, maturity and speed, thus increasing demand for such a library.

Though I love competition, standardization on certain key components speeds up adoption.

Just my two cents
Frank

**Comment by michalkalinowski-** [comment] 2016-05-02 12:29
Another one worth considering:
https://github.com/czechboy0/Jay

It builds with DEVELOPMENT-SNAPSHOT-2016-04-25-a, seems to be updated quite often and has impressive test suite.

**Comment by christiancompton** [comment] 2017-12-13 19:38
Closing - no longer relevant.

**Closed by christiancompton** 2017-12-13 19:38 UTC
