### ISSUE TITLE
New Route Cause -> Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Linicks** [IBM-Swift/Kitura#745] opened 2016-09-16 23:07 UTC
All,
  While giving the Kitura Sample a quick test drive;  I got a "Segmentation fault (core dumped)" on a route that I added.  Here is the code I added to the Main:

```
router.get("/date") { _, response, next in
     response.headers["Content-Type"] = "text/plain; charset=utf-8"
     let theDate = Date()
     try response.send("Hello the current date is: \(theDate), from Kitura!").end()
}
```

The code compiles and runs once, then I get the core dump.  Here are the logs to standard out:

```
Invoking KituraSample executable
./.build/debug/KituraSample
 VERBOSE: run() Kitura.swift line 67 - Starting Kitura framework... 
 VERBOSE: run() Kitura.swift line 69 - Starting an HTTP Server on port 8090... 
 INFO: listen(socket:port:) HTTPServer.swift line 113 - Listening on port 8090 
 INFO: listen(socket:port:) HTTPServer.swift line 118 - Accepted connection from: 127.0.0.1:38706 
 INFO: listen(socket:port:) HTTPServer.swift line 118 - Accepted connection from: 127.0.0.1:38708 
 INFO: handle(request:response:next:) main.swift line 44 - Authorization: nil 
 INFO: handle(request:response:next:) main.swift line 44 - Authorization: nil 
 INFO: listen(socket:port:) HTTPServer.swift line 118 - Accepted connection from: 127.0.0.1:38714 
 INFO: handle(request:response:next:) main.swift line 44 - Authorization: nil 
 INFO: handle(request:response:next:) main.swift line 44 - Authorization: nil 
Makefile:25: recipe for target 'run' failed
make: *** [run] Segmentation fault (core dumped)
```

Other Details:
```
--- Running build on Linux
--- Build scripts directory: Package-Builder/build
--- Checking swift version
swift --version
Swift version 3.0 (swift-3.0-GM-CANDIDATE)
Target: x86_64-unknown-linux-gnu
--- Checking swiftc version
swiftc --version
Swift version 3.0 (swift-3.0-GM-CANDIDATE)
Target: x86_64-unknown-linux-gnu
--- Checking git version
git --version
git version 2.7.4
--- Checking git revision and branch
git rev-parse HEAD
7e738d5e3c13be3cf50783d4f5646d3e5207ba5d
git rev-parse --abbrev-ref HEAD
master
--- Checking Linux release
lsb_release -d
Description:	Ubuntu 16.04.1 LTS
```

Thanks!
--Nick

**Comment by Linicks** [comment] 2016-09-19 13:24
I've updated swift to the release version of swift, and continue to get the core dump.

```
swift --version
Swift version 3.0 (swift-3.0-RELEASE)
```

-- Nick

**Comment by youming-lin** [comment] 2016-09-21 16:40
I can replicate this issue on both 16.04 and 15.10. I just have to hit `/date`, then hit a different endpoint (i.e., `/hello`), and then hit `/date` again to cause the crash. Simply refreshing page on `/date` does not cause it. I'm wondering if it's the same issue as reported [here](https://github.com/IBM-Swift/SwiftRuntime/issues/214). Simply put, there is a known issue with NSDate.description that causes crashes on Linux due to [this compiler issue](https://bugs.swift.org/browse/SR-2462). On Linux, [`Date` relies on `NSDate`'s `description` for its own `description`](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/Date.swift#L207).

**Comment by Linicks** [comment] 2016-09-22 14:22
All,
  While trying to trouble shoot this issue; I tried another framework to make sure it wasn't something that was caused by Kitura.  With the participation of that projects leaders, and some community members we determined that it was in fact an issue with swift 3.0, and I filed an issue against here (https://bugs.swift.org/browse/SR-2707).  
  I must say, that the lack of response in this community is quite alarming!  Running valid swift code that causes a hard crash every time is about as big a bug as you can have.  Even after another confirmation of the issue, no one from the core team has addressed this issue at all.  It's so disappointing to see these hollow projects taking up peoples time.  I sincerely hope that this project is able to turn itself around.  

--Nick

**Comment by ianpartridge** [comment] 2016-09-22 14:26
Hi Nick.  Youming is part of the core team and has been investigating your bug report, as you can see above.  Do you believe that https://bugs.swift.org/browse/SR-2462 and https://bugs.swift.org/browse/SR-2707 are different issues?

**Comment by Linicks** [comment] 2016-09-22 17:18
@ianpartridge ,  Thanks for taking some to address this issue!  I interpreted youming-lins post as a validation/post-mortem of the bug, and not as an engagement to try and resolve this issue.  It was the timely, and positive engagement of the other project that led me to submit the issue against Swift a couple days ago.  It's hard to believe that the use of basic Date/Time functions would be an issue with a major release version of a language.  Without doing my own full investigation, I can't be certain that SR-2462, and SR-2707 are directly related, but they do seem to share some of the same characteristics.   

"  Youming is part of the core team"

If @youming-lin is a core team member, it would be helpful if he had some kind of identification demonstrating his association with the project.  At the time of this writing, he isn't in the Kitura project contributors list:

 - https://github.com/IBM-Swift/Kitura/graphs/contributors

His Github profile doesn't suggest that he's associated with IBM, Kitura, Apple, or anyone else for that matter.   He only has a few pull requests and  a couple of forks.  

-  https://github.com/youming-lin

Clearly identifying his association with the project, would help alleviate confusion.  I hope this bug is addressed soon;  It sure puts a bad spin on swift right out of the gate. 

Thanks!
-- Nick

**Comment by ianpartridge** [comment] 2016-09-23 07:51
Agreed. I'm closing this because it's not a bug in Kitura.

**Closed by ianpartridge** 2016-09-23 07:51 UTC
