### ISSUE TITLE
Load MIME types in runtime using ContentHelper

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#118] opened 2016-02-15 15:52 UTC
The current implementation uses:

```swift 
private static let TYPES_PATH: [String] = [
        "Sources/router/contentType/types.json",
        "Packages/Phoenix/Sources/router/contentType/types.json",
        "./types.json"]
```

The types.json file will not be found at these paths. Note the version number is appended to the Packages. We will change this to use something like this found in SwiftyJSON's [BaseTests](https://github.com/IBM-Swift/SwiftyJSON/blob/master/Tests/BaseTests.swift):

```swift
 if let file = NSBundle(forClass:BaseTests.self).pathForResource("types", ofType: "json") {
            self.testData = NSData(contentsOfFile: file)
        } else {
            XCTFail("Can't find the test JSON file")
        }

```

**Comment by dfirsht** [comment] 2016-03-09 18:07
duplicate of #14

**Closed by dfirsht** 2016-03-09 18:07 UTC
Labels: enhancement
