### ISSUE TITLE
Switch from KituraTestFramework to official apple XCTest

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#186] opened 2016-02-28 17:09 UTC
It appears that the [swift-corelibs-xctest] has been implemented and stabilized that we should start migrating to this. Also, as of the latest SNAPSHOT 2-25, the Swift Package Manager launches tests with `swift test`. 

Unfortunately, like libDispatch, XCTest does not appear bundled with the SNAPSHOT. We need to build it like libDispatch. By moving to this, we could fix some of the issues we have been having with our CI building the test suite.

**Comment by rfdickerson** [comment] 2016-02-29 01:35
Ok, Mac OS build confirm runs the 11 tests successfully, but we need to get the Linux build working as well. Unfortunately, the snapshot does not include the XCTest built for us, so we have to build it ourselves.

**Comment by rfdickerson** [comment] 2016-03-01 21:56
Update: I can now build build XCTest in Linux, however there seems to be a discrepancy over the use of tearDown() in Mac OS version of XCTest and Linux's.

```shell
error: method does not override any method from its superclass
override func tearDown()
```

**Comment by rfdickerson** [comment] 2016-03-02 01:00
I have filed a bug to Apple's tracker:

[swift-test in Linux cannot find my project's C modulemaps](https://bugs.swift.org/browse/SR-856?filter=-2)

**Comment by rfdickerson** [comment] 2016-03-02 16:27
One can use [these instructions](https://gist.github.com/rfdickerson/1cf5be0dbde2bf4711e5) for setting up their Linux Swift Snapshot to run the latest XCTest and Swift Package Manager.

**Comment by rfdickerson** [comment] 2016-03-03 14:38
@vadimeisenbergibm was able to get this to work using:

```shell
swift build -Xcc -fblocks -Xcc -fmodule-map-file=Packages/Kitura-HttpParserHelper-0.3.1/module.modulemap -Xcc -fmodule-map-file=Packages/Kitura-CurlHelpers-0.3.0/module.modulemap -Xcc -fmodule-map-file=Packages/Kitura-Pcre2-0.2.0/module.modulemap && swift test
```

I can confirm it also works for me on the March 1 SNAPSHOT.

**Comment by shmuelk** [comment] 2016-03-03 14:47
In the develop branch there is no need to include the module.modulemap file for PCRE2 as we no longer use it.

**Comment by rfdickerson** [comment] 2016-03-03 16:07
I think I will fix that when I am working on #186

**Comment by rolivieri** [comment] 2016-03-03 23:15
Reopening this issue. xctest cases fail to compile/execute on linux. Just talked to vadime over slack and shared with him the issues. Vadime plans to reproduce the issues in a docker container following the instructions on the README file (develop branch). Thanks Vadime.

**Comment by vadimeisenbergibm** [comment] 2016-03-04 07:41
The problem is that XCTest lib in the docker image does not match the swift snapshot. This is because XCTtest, swift-corelibs-libdispatch and swift package manager are built separately and override the libraries in the snapshot. There is no need to do it since these libs are already included in the snapshot and, it appears, mismatch between the libraries can introduce subtle problems that are hard to detect.

The following lines should be removed from [the Dockerfile](https://github.com/IBM-Swift/swift-ubuntu-docker/blob/master/Dockerfile):
```
# Clone and install swift-corelibs-libdispatch
RUN git clone https://github.com/apple/swift-corelibs-libdispatch.git
RUN cd swift-corelibs-libdispatch && git submodule init && git submodule update && sh ./autogen.sh && ./configure --with-swift-toolchain=$WORK_DIR/$SWIFT_SNAPSHOT-$UBUNTU_VERSION/usr --prefix=$WORK_DIR/$SWIFT_SNAPSHOT-$UBUNTU_VERSION/usr && make && make install

# Clone and build Swift Package Manager
RUN git clone -b master https://github.com/apple/swift-package-manager.git
RUN ./swift-package-manager/Utilities/bootstrap --prefix $WORK_DIR/$SWIFT_SNAPSHOT-$UBUNTU_VERSION/usr install

# Download and build XCTest
RUN git clone https://github.com/apple/swift-corelibs-xctest
RUN ./swift-corelibs-xctest/build_script.py --swiftc="${WORK_DIR}/${SWIFT_SNAPSHOT}-${UBUNTU_VERSION}/usr/bin/swiftc" --build-dir="/tmp/XCTest_build" --library-install-path="${WORK_DIR}/${SWIFT_SNAPSHOT}-${UBUNTU_VERSION}/usr/lib/swift/linux" --module-install-path="${WORK_DIR}/${SWIFT_SNAPSHOT-$UBUNTU_VERSION}/usr/lib/swift/linux/x86_64"
```

**Comment by rfdickerson** [comment] 2016-03-04 15:04
Ah, yes- I think there was some issues with the timeline of when I figured out how to add XCTest to the 2-08 snapshot, and then the 3-01 snapshot had come out at the same day. I can see a future problem being introduced when the commits coming from [this pull request](https://github.com/apple/swift-package-manager/pull/158) enter the next snapshot, right?

**Comment by rfdickerson** [comment] 2016-03-08 14:15
The following merged PR apparently will fix our problem that 'swift test' needs to manually point to modulemaps. Instead, we can do swift test without arguments.

https://github.com/apple/swift-package-manager/pull/181

**Comment by rolivieri** [comment] 2016-03-08 16:07
@vadimeisenbergibm - Is there anything else you need to investigate regarding this issue? If not, I am thinking we can close it. We have validated that we now have tests using the official xctests running on both platforms (os x and linux)... though, yes, different compiler options are needed. We can open a different issue for that. Thoughts?

**Comment by vadimeisenbergibm** [comment] 2016-03-08 17:17
@rolivieri I am closing the issue. Once we switch to official snapshot with apple/swift-package-manager#181 inside, the compiler flags will be the same.

**Closed by vadimeisenbergibm** 2016-03-08 17:17 UTC
Labels: tests
