### ISSUE TITLE
KituraNet Xcode Build failed

### ISSUE THREAD

**Issue by aquarchitect** [IBM-Swift/Kitura#463] opened 2016-05-10 15:55 UTC
I got this error with __05.03 Snapshot__ and __0.13.2 Kitura__ when trying to build in Xcode while terminal build with `swift build` works perfectly fine.

![KituraNet Xcode Build Error](https://cloud.githubusercontent.com/assets/8365795/15152890/e0e07c60-168b-11e6-954d-0c26fc25ff96.png)

I guess something to due with the __Build Settings__. Any idea how to fix is greatly appreciated.

**Comment by kweinmeister** [comment] 2016-05-10 16:19
I just tried the following with 5/3 snapshot configured on both my PATH and Xcode toolchain:
* Pull latest from Kitura-Net develop branch
* Deleted Packages subdirectory and my existing Kitura-net.xcodeproj
* Ran `swift build -X`

Seems to build fine and the tests passed. I looked in the Build Settings, and I don't have anything set there for either Header Search Paths or Library Search Paths.

Can you try again using the steps above?

**Comment by aquarchitect** [comment] 2016-05-10 16:47
Thanks for taking a look for me. Yup, I have tried `swift build --clean`, removed the `Packages` directory, and even cleaned up the `DerivedData`; i still got the same problem. 

The difference is that I have Header Search Paths of both `KituraNet` and `Kirura` targets pointed to the CHttpParser (I didn't set this).

![](https://cloud.githubusercontent.com/assets/8365795/15154754/14ea7fa8-1694-11e6-8810-44911153d5e1.png)

**Comment by kweinmeister** [comment] 2016-05-10 19:48
Can you try adding `${SRCROOT}/.build/debug` to the Library Search Paths for the KituraNet target?

**Comment by aquarchitect** [comment] 2016-05-10 20:29
That seems to fix the `KituraNet` issue, but got the new one :|.

![](https://cloud.githubusercontent.com/assets/8365795/15161378/d7573fc2-16b2-11e6-8f8d-52a13fd33bbb.png)

**Comment by zzyyzz1992** [comment] 2016-05-11 01:50
got the exact same errors in my practice.
I followed [this](https://github.com/IBM-Swift/Kitura#developing-kitura-applications)
swift build & run with no problem,
but got above same error using swift build -X

**Comment by zzyyzz1992** [comment] 2016-05-11 01:55
And this #459 issue might be related.

**Comment by kweinmeister** [comment] 2016-05-11 02:01
Thanks @zzyyzz1992. Closing this one as a duplicate of #459

**Closed by kweinmeister** 2016-05-11 02:01 UTC
