### ISSUE TITLE
Router failed to send response

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Kitura#444] opened 2016-05-05 09:20 UTC
Applying load to the frontpage of Kitura-Sample, the log shows repeated errors:

```
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58659
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58660
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58662
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58665
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58666
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58668
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58670
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58672
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58674
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58676
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58678
 INFO: handle(request:response:next:) main.swift line 46 - Authorization: nil
 INFO: handle(request:response:next:) main.swift line 46 - Authorization: nil
 INFO: handle(request:response:next:) main.swift line 46 - Authorization: nil
 INFO: handle(request:response:next:) main.swift line 46 - Authorization: nil
 ERROR: handle(request:response:) Router.swift line 676 - Failed to send response to the client
 ERROR: handle(request:response:) Router.swift line 676 - Failed to send response to the client
 INFO: spiListen(socket:port:) HttpServerSpi.swift line 53 - Accepted connection from: 127.0.0.1:58680
 ERROR: handle(request:response:) Router.swift line 676 - Failed to send response to the client
 ERROR: handle(request:response:) Router.swift line 676 - Failed to send response to the client
```

**Comment by tunniclm** [comment] 2016-05-09 16:10
I tried to recreate this on `master` on commits 7271233091d44efb89a65cfc7f441d532a48c638 and f0dbbb14604146c11ef0f6e1a5b3aecca05833e5 without success.

My tests were using the vagrant image on a Linux host and `ab` (the Apache HTTP server benchmarking tool). I tried several different runs of `ab` including `ab -c 4 -n 5000` but saw no failures on any attempts.

**Comment by shmuelk** [comment] 2016-05-09 17:10
Some of these errors on the driving side may be due to the use of Keep Alive, which we don't support at this time.

I hope to add in the next couple of days to a week or so.

**Comment by dfirsht** [comment] 2016-05-16 20:18
I am unable to reproduce this as well. I am going to close this for now then. We can reopen if it comes up again.

**Closed by dfirsht** 2016-05-16 20:18 UTC
