### ISSUE TITLE
Static File Server Unable To Serve Alternate Home Page

### ISSUE THREAD

**Issue by JonKaleidoscope** [IBM-Swift/Kitura#1345] opened 2018-10-11 04:18 UTC
## Context and Description
I am unable to serve an home page using the `StaticFileServer`
`localhost:8080/`

### Steps to Reproduce
1) Create alternate home page lets call it index2.html save it in `./public` of project folder
2) Register new route with new home page:
```swift
router.get("/", middleware:  StaticFileServer(path: "./public/index2.html"))
```
3) Go to top index home page index, ie `localhost:8080/`

### Expected vs. Actual Behaviour
- [ ] Expected `index2.html` page to be loaded and displayed
- [ ] Actual behavior showed the default Kitura homepage

Able to serve alternive route just fine:

```swift
 router.get("/index2", middleware:  StaticFileServer(path: "./public/index2.html"))
```

The issue appears to be occurring in ` func getFilePath(from request: RouterRequest) -> String?` of the `FileServer` class.

I will say `/` is a tricky route.

In addition the `/*` is not serving the other items in custom public folder; 302's are getting returned.
```swift
router.get("/*", middleware:  StaticFileServer(path: "<path-to-public-folder>"))
```
`localhost:8080/index2.html` returns 302

**Comment by ddunn2** [comment] 2018-10-29 13:55
Hey @JonKaleidoscope 

Thanks for raising this issue and for doing some debugging around this issue.

**Comment by kilnerm** [comment] 2019-01-11 17:05
@JonKaleidoscope Apologies for the time it has taken to get back to you.

I have taken a look at the issue and I think there are a combination of factors in play here.

Firstly the `StaticFileServer` is expecting a root folder to be passed to the initialiser, I think this is something that should be fixed to reject anything other than a folder.

Secondly when you specify your second route:

`router.get("/index2", middleware:  StaticFileServer(path: "./public/index2.html”))`

the serving path is returned as the base serving path and as the index2.html file exists it is successfully served. This happens because the code is written to serve from a folder and the fix above would resolve this issue also.

The static file server can serve an alternate homepage to the default splash page on the default route, you should simply place a file named index.html in your serving folder and define a route such as:

`router.get("/", middleware: StaticFileServer(path: "./test”))`

When accessing your server on / the contents of index.html will be served. You can also use /<file> to access any other file in the serving folder.

**Comment by kilnerm** [comment] 2019-01-23 09:39
I have merged a fix to log a warning / error when the `StaticFileServer` is not being used as intended.

I have also added making the initialiser failable to the list of things to do before the next major release.

**Comment by JonKaleidoscope** [comment] 2019-01-23 14:47
@kilnerm Thanks for the clarification, I will take these notes into consideration moving forward.

**Closed** 2019-01-29 07:37 UTC
