### ISSUE TITLE
XCode Breakpoint

### ISSUE THREAD

**Issue by macfeteria** [IBM-Swift/Kitura#414] opened 2016-04-24 18:24 UTC
I always get an error message if I add a breakpoint after Kitura start. 

ERROR: spiListen(_:port:) /Kitura-Sample/Packages/Kitura-net-0.7.2/Sources/KituraNet/HttpServerSpi.swift line 63 - Error reported:
 Error code: -9994, Interrupted system call
[Demo](https://www.youtube.com/watch?v=bW_x5KGLi10)
However If I add a breakpoint before the program start , XCode doesn't show an error message.

**Comment by NikitaSullivan** [comment] 2016-04-26 13:41
Hi macfeteria,

Thank you for finding and raising this issue and for the information and demo you've provided, it'll really help once someone picks this up.

Best Regards,
Nikita Sullivan
Swift@IBM

**Comment by dfirsht** [comment] 2016-04-26 18:17
Hmm just by taking a glance it seems as if the break point is interrupting the system call to `accept` that BlueSocket calls. I don't think there is anyway to avoid this issue besides moving the breakpoint. @billabt have you seen anything like this?

**Comment by billabt** [comment] 2016-04-26 19:00
Yes, this going to happen.  I ran into it all the time while debugging this originally,  The best way is set the breakpoint where you need it and then restart the app. There appears to be no way around it that I can find so far.

**Comment by macfeteria** [comment] 2016-04-27 15:00
OK, I see.
Thank you for your suggestion.

**Comment by shmuelk** [comment] 2016-04-27 17:46
@billabt There is actually a very simple way around the problem of setting a breakpoint while the server is running. We actually had it in our the socket code we in Haifa wrote at the beginning of our Kitura work.

The problem is that the system call accept (the blocking one there) is interrupted when you set a breakpoint. You need to check the error code for EINT, I think, and simply retry the call.

**Comment by billabt** [comment] 2016-04-27 17:48
@shmuelk: Cool.  I'll put it in.

**Comment by billabt** [comment] 2016-04-27 18:13
This is fixed with **BlueSocket v0.5.1**.  You can now set breakpoints without causing problems.

**Closed by billabt** 2016-04-27 18:13 UTC
