### ISSUE TITLE
Kitura should return 405 status codes when method is wrong

### ISSUE THREAD

**Issue by akrabat** [IBM-Swift/Kitura#799] opened 2016-10-06 14:51 UTC
Given:

```swift
router.get("/hello") { _, response, next in
    response.status(.OK).send(json: JSON(["hello" : "world"]))
    next()
}
```

Then:

```
curl -i -X PUT  http://localhost:8090/hello
```

Should return a status code of ``405 Method Not Allowed``

**Comment by ianpartridge** [comment] 2016-10-06 15:04
What does it return at the moment?

**Comment by akrabat** [comment] 2016-10-06 19:47
A 404

**Comment by youming-lin** [comment] 2016-10-06 20:44
Related: https://github.com/IBM-Swift/Kitura/issues/689

FYI, Node Express also returns a 404 in this scenario, so Kitura is following Node Express's convention.

**Comment by kweinmeister** [comment] 2016-10-06 20:47
@akrabat Are there any other frameworks you're aware of that return a 405? Or, is there a spec that defines the expected behavior?

**Comment by youming-lin** [comment] 2016-10-06 20:54
Ideally, we should be as specific as possible wrt to HTTP status codes. HTTP does allow for [405 Method Not Allowed](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html); however, it also specifies that the server MUST respond with a list of valid methods, which requires more processing in Kitura (to look through all handlers for the route and check their methods). As route handling can become complex through the use of subrouters (and subrouters of subrouters, so on and so forth), I'm not sure if it's efficient/feasible to discover a list of allowed methods.

**Comment by akrabat** [comment] 2016-10-07 07:24
@kweinmeister Every PHP and Python framework I've used has returned 405 in this situation. Admittedly, I've only used a very small subset of all the frameworks out there!

@youming-lin: Related, Kitura should support OPTIONS automatically too - in which case the `Allowed` header on the 405 response would use the same logic.

**Comment by youming-lin** [comment] 2016-10-19 15:27
Closing this due to the complexity of potential implementation vs. benefits obtained. The capability of wildcard matching coupled with the lack of guarantee for a path handler to invoke `response.end()` makes this check nontrivial.

Node express had a similar discussion and ultimately decided against returning 405: https://github.com/expressjs/express/issues/1895

I think [this comment](https://github.com/expressjs/express/issues/1895#issuecomment-31816494) sums up the complexity of implementing 405 correctly.

**Closed by youming-lin** 2016-10-19 15:27 UTC
