### ISSUE TITLE
Memory leak when executing HTTP.request(...)

### ISSUE THREAD

**Issue by michalkalinowski-** [IBM-Swift/Kitura#548] opened 2016-06-22 09:48 UTC
Hello,

I found a severe memory leak when using ClientRequest class from KituraNet. Executing just 300 requests leaked around 45MB of memory 0_0. From what i see the main leaks happen when opening curl session, but I'm no leak-finding expert.

**Steps to reproduce:**

```swift
import KituraNet // 0.19.0

for i in 1..<1000 {
  let request = HTTP.request("https://google.com") {
    response in
    print(response?.statusCode)
  }
  request.end()
}
```

I have only tested this on OSX, can somebody( @djones6 , @ianpartridge ?) please confirm the same happens on Linux? I have no knowledge of Linux profiling tools.

**Comment by ianpartridge** [comment] 2016-06-22 10:30
Thanks for the report, @michalkalinowski-. @djones6 is on holiday at the moment. I'll take a look at this and try and reproduce the issue. I know @djones6 was using [massif](http://valgrind.org/docs/manual/ms-manual.html) on Linux for his earlier heap profiling work.

**Comment by dfirsht** [comment] 2016-07-11 21:35
I believe this has been fixed, @ianpartridge can you confirm?

**Comment by michalkalinowski-** [comment] 2016-08-12 13:01
I still see this issue using Kitura-net-0.26.0 on OSX

**Comment by ianpartridge** [comment] 2016-08-12 13:06
Thanks Michal, we'll take another look.

**Comment by ianpartridge** [comment] 2016-08-16 19:49
@michalkalinowski- The commit above fixes this for me. Thank you for reporting this!

**Comment by djones6** [comment] 2016-08-31 16:22
Progress update:  there is a memory leak in the error path in `ClientRequest.end()` where the `ClientResponse` has a strong reference cycle with the `HTTPParser` which is never broken (similar to the one seen in #655).

Fixing this resolves the significant leak which you would experience if repeatedly issuing a request to a URL that fails.  I've pushed a fix to the Kitura-net issue_548 branch.

A second leak remains and seems to be related to strings passed to CCurl (such as headers and the request URL). From a first look, everything seems to be in order in terms of the curl cleanup functions being called in the right places, so I need to look closer.

**Comment by ianpartridge** [comment] 2016-09-20 09:22
After discussion we don't currently plan to pursue the remaining leak, as this code is going to be deprecated in favour of Kitura-Request anyway.  Closing this issue.

**Closed by ianpartridge** 2016-09-20 09:22 UTC
Labels: bug
