### ISSUE TITLE
Illegal instruction: 4 throw while benchmarking

### ISSUE THREAD

**Issue by wildfiremedia** [IBM-Swift/Kitura#780] opened 2016-10-01 16:49 UTC
First, there are amazing improvement in the request score and I do find the memory will increase to 30MB+ while running benchmark unlike Perfect 2 which could maintain at 7MB+ which is a mystery.

```
yanlis-MacBook-Pro:h yanli$ wrk -t2 -c200 -d30 http://localhost:8090
Running 30s test @ http://localhost:8090
  2 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.98ms    3.34ms  73.71ms   68.84%
    Req/Sec    10.47k     1.91k   16.22k    66.50%
  626549 requests in 30.08s, 86.37MB read
  Socket errors: connect 0, read 39, write 0, timeout 0
Requests/sec:  20826.28
Transfer/sec:      2.87MB
```

terminal:

```
yanlis-MacBook-Pro:myFirstProject yanli$ ./.build/release/myFirstProject
Illegal instruction: 4
```

**Comment by ianpartridge** [comment] 2016-10-03 09:54
Thanks for reporting this `Illegal instruction: 4` issue.

Do you have a GitHub project we can clone to reproduce this issue?

**Comment by wildfiremedia** [comment] 2016-10-03 10:04
Nope, I just follow your first tutorial and ran on macOS 10.12 and Xcode 8
(8A218a). Kitura will abnormally terminated the moment wrk benchmark
completed.

**Comment by ianpartridge** [comment] 2016-10-03 10:06
Were you building Kitura from inside Xcode, or from the command-line via `swift build`?

**Comment by wildfiremedia** [comment] 2016-10-03 10:07
command line using swift build -c release

**Comment by ianpartridge** [comment] 2016-10-03 10:18
[This link](http://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10) suggests that it may be because the binaries were compiled with an incompatible instruction set.  Very odd.  I'll try and reproduce this myself.

**Comment by ianpartridge** [comment] 2016-10-03 12:31
I can reproduce this myself, running https://github.com/IBM-Swift/Kitura-Sample

**Comment by ianpartridge** [comment] 2016-10-03 12:35
Here's the lldb backtrace: https://gist.github.com/ianpartridge/ab666c923e3c955dc1700f39ad38535f

**Comment by ianpartridge** [comment] 2016-10-03 13:04
This looks very like https://github.com/IBM-Swift/Kitura/issues/784 however when I apply the patch for that bug, I see a different crash:

```
2016-10-03 13:58:27.479694 KituraSample[19872:1399913] fatal error: attempting to access Dictionary elements using an invalid Index
Current stack trace:
0    libswiftCore.dylib                 0x000000010084d3e0 swift_reportError + 125
1    libswiftCore.dylib                 0x0000000100868c80 _swift_stdlib_reportFatalError + 61
2    libswiftCore.dylib                 0x0000000100647c40 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
3    libswiftCore.dylib                 0x00000001007d8bc0 partial apply for (_fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never).(closure #2) + 109
4    libswiftCore.dylib                 0x0000000100647c40 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
5    libswiftCore.dylib                 0x00000001007906e0 specialized _fatalErrorMessage(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never + 96
 INFO: handle(request:response:next:) main.swift line 45 - Authorization: nil 
6    libswiftCore.dylib                 0x000000010069b900 _NativeDictionaryStorage.assertingGet(_NativeDictionaryIndex<A, B>) -> (key : A, value : B) + 330
7    libswiftCore.dylib                 0x00000001006b1cf0 DictionaryIterator._nativeNext() -> (key : A, value : B)? + 619
8    libswiftCore.dylib                 0x000000010069b260 DictionaryIterator.next() -> (key : A, value : B)? + 35
9    KituraNet                          0x0000000100197a30 HTTPServerResponse.flushStart() throws -> () + 1680
10   KituraNet                          0x0000000100197360 HTTPServerResponse.write(from : Data) throws -> () + 100
...
```

More investigation needed.

**Comment by ianpartridge** [comment] 2016-11-30 15:51
We think this may be fixed by https://github.com/IBM-Swift/Kitura-net/commit/d47f9910aa1987b15e873ce636d9cac9d2be4a0c - I will check.

**Comment by ianpartridge** [comment] 2016-12-09 16:00
Confirmed fixed.

**Closed by ianpartridge** 2016-12-09 16:00 UTC
Labels: bug
