### ISSUE TITLE
Crash - pointer being freed was not allocated

### ISSUE THREAD

**Issue by chrisozenne** [IBM-Swift/Kitura#224] opened 2016-03-03 23:20 UTC
I'm getting a crash when running Kitura with Kitura-redis.

`myFirstProject(72926,0x700000187000) malloc: *** error for object 0x7f8ca8e04b50: pointer being freed was not allocated`

It seems that my code is executed properly as I receive a response from the server, but then the server crashes and I'm not sure how to go about debugging this. Can someone here point me in the right direction? Thanks!

Here's the code which crashes:

```
router.get("/visits", handler: {
    request, response, next in
    
    let redis = Redis()
    redis.connect("localhost", port: 6379, callback: { (error: NSError?) in
        if let error = error {
            Log.verbose(error.localizedDescription)
        } else {
            redis.incr("visits", by: 1, callback: { (visits: Int?, error: NSError?) in
                if let error = error {
                    Log.verbose(error.localizedDescription)
                } else {
                    if let visits = visits {
                        response.status(HttpStatusCode.OK).send("Visits: \(visits)")
                        next()
                    }
                }
            })
        }
    })
})
```

**Comment by dfirsht** [comment] 2016-03-14 19:44
hmm not sure exactly, but next should be called for every condition

**Comment by dfirsht** [comment] 2016-04-19 19:30
Hey @chrisozenne I want to follow up on this issue. Is this still happening in the latest version of Kitura? If you are interested, we can look at your project and see if we can figure out what's going on.

**Comment by chrisozenne** [comment] 2016-04-19 19:33
I haven't tried using Redis since I posted this over a month ago.

**Comment by dfirsht** [comment] 2016-04-19 20:32
Sorry for the long delay @chrisozenne, we have been focused on development in the past but are now trying to make a renewed effort to address community issues. If there is anything we can do for you now, please let us know.

**Comment by chrisozenne** [comment] 2016-04-19 22:08
I'm glad to hear so. I was beginning to write a tutorial series on Kitura, but decided that the timing isn't quite right yet. For example, I have a pull request for Kitura-CouchDB which is now over a month old and being ignored: https://github.com/IBM-Swift/Kitura-CouchDB/pull/5

**Comment by shmuelk** [comment] 2016-05-08 15:47
This is a duplicate of IBM-Swift/Kitura-redis#5

**Closed** 2016-05-08 15:56 UTC
Labels: bug
