### ISSUE TITLE
[StaticFileServer] Option to fall back to index.html on 404 not found

### ISSUE THREAD

**Issue by RahulKatariya** [IBM-Swift/Kitura#1329] opened 2018-09-07 09:39 UTC
## Context and Description
I am building an application with React and Browser Router. As it is a single page application, it requires to fall back to index.html on 404 not found.

**Note**: It works fine with the hash-based routing where URLs have `#` like `https://localhost:8080/#/index.html` but this type of routing doesn't use HTML5 history API and loses the state when navigating back and forward through the browser controls.

Related Resources: 
1. https://github.com/bripkens/connect-history-api-fallback
2. https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback
3. https://developer.mozilla.org/en-US/docs/Web/API/History

### Environment Details
Information about your OS, Swift version and Xcode version if on macOS.
Swift: 4.1.2

### Steps to Reproduce
The StaticFileServer used with any front-end framework (Angular, React or Vue) and Browser router instead of Hash router will reproduce the issue.

### Expected vs. Actual Behaviour
The expected behaviour is to fall back to index.html and the application takes care of the routing while the Kitura framework responded with `Cannot GET /{PATH}`

**Comment by kilnerm** [comment] 2018-09-13 11:59
It appears the behavior requested is present on other run-times the provide file server capabilities.

We will need to add this functionality via a configuration option on the static file server so users can create file servers that exhibit this behavior.

**Comment by pushkarnk** [comment] 2019-04-25 08:09
Received a sample that reproduces the problem from Rahul. I played around and can see the problem. Thanks @RahulKatariya

**Comment by pushkarnk** [comment] 2019-04-26 08:15
Prototyped a new `StaticFileServer.Option` named `fallbackToDefaultIndex` 
https://github.com/pushkarnk/Kitura/commit/718d6a21e528d0c603a053f104604b0dfa1787d9

Got the running webapp reviewed from Rahul. The expectation is a little different from what I had assumed: on the user trying to bypass the landing page and accessing a location directly, the default landing location (like `/index.html`) must be rendered, but the user entered path must be retained. For example, if the user tries to access `/user/report`, the index.html pertaining to  `localhost:8080` must be rendered but the path must be retained as `localhost:8080/user/report`

**Comment by pushkarnk** [comment] 2019-04-26 08:18
The feedback above means a few more changes to the prototype. 

Apart from that, there are a few things to take care of here(just thinking aloud):
1. The user must be able to configure the fallback location. The default could be `/index.html`.
2. No fallback if the user is trying to directly access a file
3. The user must be able to configure locations for which the fallback fails

**Comment by pushkarnk** [comment] 2019-05-30 06:45
> Prototyped a new `StaticFileServer.Option` named `fallbackToDefaultIndex`
> [pushkarnk@718d6a2](https://github.com/pushkarnk/Kitura/commit/718d6a21e528d0c603a053f104604b0dfa1787d9)
> 
> Got the running webapp reviewed from Rahul. The expectation is a little different from what I had assumed: on the user trying to bypass the landing page and accessing a location directly, the default landing location (like `/index.html`) must be rendered, but the user entered path must be retained. For example, if the user tries to access `/user/report`, the index.html pertaining to `localhost:8080` must be rendered but the path must be retained as `localhost:8080/user/report`

Redirecting without changing the URL is implementable in Kitura. I tried serving the `/index.html` for invalid paths but it doesn't get rendered because the client-side still hides/shows divs based on the path. Will discuss this with Rahul.

**Comment by pushkarnk** [comment] 2019-06-14 08:45
I had the prototyped behaviour, with a fallback option, reviewed by Rahul and he thinks it is OK. Created PR #1464 for this enhancement. Doc changes pending.

**Comment by djones6** [comment] 2019-08-05 08:34
1464 is now merged, and will be tagged soon.

**Closed by djones6** 2019-08-05 08:34 UTC
Labels: User request, enhancement

**Comment by djones6** [comment] 2019-08-12 15:39
This is now tagged in Kitura `2.8.0`.
