### ISSUE TITLE
StaticFileServer for serving files at web site root ("/") not working

### ISSUE THREAD

**Issue by dsperling** [IBM-Swift/Kitura#837] opened 2016-11-04 16:06 UTC
This router entry worked in Kitura 1.0 to serve a web site, and does not seem to work in Kitura 1.1.

`router.get("/", middleware: StaticFileServer())`

This was used to serve files fro directories such as:
/
/img
/css
etc...

Did something change in the routing logic in 1.1?  I don't see any recent changes to the StaticFileServer code.

I will post an example later today to demonstrate the problem.

**Comment by youming-lin** [comment] 2016-11-04 16:33
Related to #821.

**Comment by rolivieri** [comment] 2016-11-08 20:01
@youming-lin Is there an ETA on the fix for this? This broke the kitura-starter sample app -> static content not served.

**Comment by youming-lin** [comment] 2016-11-08 20:10
@rolivieri I've found the cause of the issue and is currently working on a fix. ETA two more days, no guarantees though.

**Comment by dsperling** [comment] 2016-11-08 20:25
I was going to put together a sample app to demonstrate the issue, but it looks like we can duplicate things with https://github.com/IBM-Swift/Kitura-Sample.  If you still need an example project, let me know.

**Comment by ianpartridge** [comment] 2016-11-14 13:42
Hi @youming-lin is this fixed now? If so, please move to Validate :)

**Comment by youming-lin** [comment] 2016-11-14 15:33
@ianpartridge Not yet, it's currently awaiting review: #845

**Comment by youming-lin** [comment] 2016-11-14 19:36
PR has been merged. Fix should be in Kitura 1.1.2 now.

**Closed by youming-lin** 2016-11-14 19:36 UTC
Labels: bug
