### ISSUE TITLE
SwiftyJSON: On Linux .bool always returns Optional(false)

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Kitura#568] opened 2016-06-29 18:15 UTC
This simple test case prints Optional(true) on macOS and Optional(false) on Linux:

```swift
import Foundation
import SwiftyJSON

let data = "{\"test\": true}".data(using: NSUTF8StringEncoding)!                                                   
let json = JSON(data: data)
print(json["test"].bool)
```

(Using Swift 3 Snapshot 2016-06-06

**Comment by tunniclm** [comment] 2016-06-29 18:17
NOTE: Posting this here at suggsestion of @dfirsht because I couldn't post an issue on IBM-Swift/SwiftyJSON and I haven't checked if it is recreatable in Swift 2 so I didn't want to post it on SwiftyJSON/SwiftJSON either.

**Comment by irar2** [comment] 2016-07-20 12:09
testBool in RawRepresentableTests fails because of this problem. I disabled this test on Linux in testupdates branch for now.

**Comment by youming-lin** [comment] 2016-07-20 15:21
Issue is caused by the use of `.rawBool` instead of `.rawNumber` in Linux vs. macOS. I've opened PR against IBM-Swift/SwiftyJSON.

**Comment by youming-lin** [comment] 2016-07-26 18:35
Should be fixed now. Code was delivered in https://github.com/IBM-Swift/SwiftyJSON/pull/7.

**Closed by youming-lin** 2016-07-26 18:35 UTC
Labels: bug
