### ISSUE TITLE
Investigate how to bind variables defined in Bluemix to a Swift application

### ISSUE THREAD

**Issue by dfirsht** [IBM-Swift/Kitura#46] opened 2016-02-08 16:51 UTC
<a href="https://github.ibm.com/ricardo-olivieri"><img src="https://avatars.github.ibm.com/u/1573?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ricardo-olivieri](https://github.ibm.com/ricardo-olivieri)**
_Thursday Jan 14, 2016 at 16:49 GMT_
_Originally opened as https://github.ibm.com/ibmswift/Phoenix/issues/46_

----

**Comment by rfdickerson** [comment] 2016-03-03 18:29
We should follow [cfenv Node Package API](https://www.npmjs.com/package/cfenv) very similarly, since that's what developers are used to using.

**Comment by rfdickerson** [comment] 2016-03-28 14:32
This is a duplicate of @rolivieri issue where he's creating a CFenv, right?

**Closed by rfdickerson** 2016-03-28 14:32 UTC
